apiVersion: v1
kind: Secret
metadata:
  name: opensearch-auth
type: Opaque
data:
  # Base64 encoded: echo -n 'admin' | base64
  username: YWRtaW4= 
  # Base64 encoded: echo -n 'Pass@123@pass' | base64
  password: UGFzc0AxMjNAcGFzcw==
